### PR TITLE
Feature: Add NDS and 3DS token support

### PR DESCRIPTION
**Pull request by dcramer**
Adds support for .nds and .3ds to GameConsole.

Currently on supports batocera for output tokens.

### CODE REVIEW

**Comment by dcramer** [comment]
Couldn't find a canonical example for mister/pocket, and at leastOnion doesnt seem to list support. I _think_ this is all thats needed, but testing it now.

**Comment by dcramer** [comment]
Aside couldn't tell if you had tests for specifically this level of detail, but if so lmk and I'll add to them

**Comment by emmercm** [comment]
I'm fairly sure those other frontends don't support NDS and 3DS, NDS emulation seems out of reach for SBC handhelds right now. Feel free to drop those TODO comments and I can merge this in.

I don't have comprehensive tests for every console and token combination, but maybe this will get to a point when some will be needed.

Thank you for your contribution!

**Review by emmercm — CHANGES_REQUESTED** [review]
Previous comment

**Comment by dcramer** [comment]
Should be all set

**Review by emmercm — APPROVED** [review]

**Pull request merged**
