### PR TITLE
Feature: update console support

### PR DESCRIPTION
**Pull request by juliadin**
I am currently going through the lists of supported consoles and adding things, fixing things.

I am also introducing the {console} token that is replaced with the more or less canonical name of the console. I hope that’s ok. It’s a more specific way of doing things than the `—dir-dat-name` which largely depends on the dat creators view on the name (which differs between groups). I tried to get the different names from different regions into one string, trying to respect POSIX and Windows file system limitations. It would be useful for my collection at least, feel free to shoot the idea down though :).

### CODE REVIEW

**Comment by emmercm** [comment]
@juliadin I scanned through the diff so far and it looks good to me. I would probably personally err on the side of using console names copied & pasted from No-Intro DATs, as those are seemingly the most used DATs these days.

Do you have any consoles you're not sure about?

**Comment by emmercm** [comment]
Something worth thinking about @juliadin is what is the use case for this over `{datName}`? Maybe it would help sort ROMs when not using DATs, but it would likely drop a lot of data if it can't find an appropriate `{console}` using filename extensions. Whatever we do here will be just as opinionated as the naming used in DATs, and it might be best to encourage people to just use DATs that they prefer best.

**Comment by juliadin** [comment]
In the end this is https://xkcd.com/927/ all over again but the usecase would be that by using regex igir could bring many opinionated namings into one opinionated naming ... I still think it is worth the work.

**Comment by emmercm** [comment]
I see the use case for mixing multiple input DATs, though I typically don't because it's highly likely duplicate ROMs will be output with different filenames. Though there is normally not a ton of overlap between No-Intro and Redump.

I'm good with this if you are, I don't see a ton of harm in it, and I think documentation will go a long way toward clearing up any confusion.

**Comment by juliadin** [comment]
After thinking about it for a while I guess you are right. While the main task of the pull request still makes sense (adding as many .dat Regexes for game systems as possible and finding out if any supported emulation devices can work with these) my draft for a new tag doesn't ... it just adds to the confusion that working with .dats can be as it is. What turned it around for me was that especially the dats for working with game systems that support multiple formats or where formats matter this makes things harder, not easier. It seemed like a good idea and seemed to solve a problem I thought I had. Thanks for helping me think about it again :).

**Pull request closed without merging**
